// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        (unknown)
// source: universe_rpc.proto

package universe_rpc

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SolarSystemStats struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Age float64 `protobuf:"fixed64,1,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *SolarSystemStats) Reset() {
	*x = SolarSystemStats{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universe_rpc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SolarSystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolarSystemStats) ProtoMessage() {}

func (x *SolarSystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_universe_rpc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolarSystemStats.ProtoReflect.Descriptor instead.
func (*SolarSystemStats) Descriptor() ([]byte, []int) {
	return file_universe_rpc_proto_rawDescGZIP(), []int{0}
}

func (x *SolarSystemStats) GetAge() float64 {
	if x != nil {
		return x.Age
	}
	return 0
}

// The request message containing the user's name.
type BodyName struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *BodyName) Reset() {
	*x = BodyName{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universe_rpc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyName) ProtoMessage() {}

func (x *BodyName) ProtoReflect() protoreflect.Message {
	mi := &file_universe_rpc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyName.ProtoReflect.Descriptor instead.
func (*BodyName) Descriptor() ([]byte, []int) {
	return file_universe_rpc_proto_rawDescGZIP(), []int{1}
}

func (x *BodyName) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// The response message containing the greetings
type BodyPos struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X    float64 `protobuf:"fixed64,1,opt,name=x,proto3" json:"x,omitempty"`
	Y    float64 `protobuf:"fixed64,2,opt,name=y,proto3" json:"y,omitempty"`
	Vx   float64 `protobuf:"fixed64,3,opt,name=vx,proto3" json:"vx,omitempty"`
	Vy   float64 `protobuf:"fixed64,4,opt,name=vy,proto3" json:"vy,omitempty"`
	Mass float64 `protobuf:"fixed64,5,opt,name=mass,proto3" json:"mass,omitempty"`
}

func (x *BodyPos) Reset() {
	*x = BodyPos{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universe_rpc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodyPos) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodyPos) ProtoMessage() {}

func (x *BodyPos) ProtoReflect() protoreflect.Message {
	mi := &file_universe_rpc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodyPos.ProtoReflect.Descriptor instead.
func (*BodyPos) Descriptor() ([]byte, []int) {
	return file_universe_rpc_proto_rawDescGZIP(), []int{2}
}

func (x *BodyPos) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BodyPos) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BodyPos) GetVx() float64 {
	if x != nil {
		return x.Vx
	}
	return 0
}

func (x *BodyPos) GetVy() float64 {
	if x != nil {
		return x.Vy
	}
	return 0
}

func (x *BodyPos) GetMass() float64 {
	if x != nil {
		return x.Mass
	}
	return 0
}

type AllBodies struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Bodies map[string]*BodyPos `protobuf:"bytes,1,rep,name=Bodies,json=bodies,proto3" json:"Bodies,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *AllBodies) Reset() {
	*x = AllBodies{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universe_rpc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AllBodies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllBodies) ProtoMessage() {}

func (x *AllBodies) ProtoReflect() protoreflect.Message {
	mi := &file_universe_rpc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllBodies.ProtoReflect.Descriptor instead.
func (*AllBodies) Descriptor() ([]byte, []int) {
	return file_universe_rpc_proto_rawDescGZIP(), []int{3}
}

func (x *AllBodies) GetBodies() map[string]*BodyPos {
	if x != nil {
		return x.Bodies
	}
	return nil
}

type NoInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NoInput) Reset() {
	*x = NoInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_universe_rpc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NoInput) ProtoMessage() {}

func (x *NoInput) ProtoReflect() protoreflect.Message {
	mi := &file_universe_rpc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NoInput.ProtoReflect.Descriptor instead.
func (*NoInput) Descriptor() ([]byte, []int) {
	return file_universe_rpc_proto_rawDescGZIP(), []int{4}
}

var File_universe_rpc_proto protoreflect.FileDescriptor

var file_universe_rpc_proto_rawDesc = []byte{
	0x0a, 0x12, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x24, 0x0a, 0x10, 0x53, 0x6f, 0x6c, 0x61, 0x72, 0x53, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x03, 0x61, 0x67, 0x65, 0x22, 0x1e, 0x0a, 0x08, 0x42, 0x6f,
	0x64, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x59, 0x0a, 0x07, 0x42, 0x6f,
	0x64, 0x79, 0x50, 0x6f, 0x73, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01,
	0x52, 0x01, 0x78, 0x12, 0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x01,
	0x79, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x76,
	0x78, 0x12, 0x0e, 0x0a, 0x02, 0x76, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x01, 0x52, 0x02, 0x76,
	0x79, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x61, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x04, 0x6d, 0x61, 0x73, 0x73, 0x22, 0x80, 0x01, 0x0a, 0x09, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x64,
	0x69, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x06, 0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x2e,
	0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x62, 0x6f, 0x64,
	0x69, 0x65, 0x73, 0x1a, 0x43, 0x0a, 0x0b, 0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x1e, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x50, 0x6f, 0x73, 0x52, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x09, 0x0a, 0x07, 0x4e, 0x6f, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x32, 0xd5, 0x01, 0x0a, 0x07, 0x47, 0x72, 0x65, 0x65, 0x74, 0x65, 0x72, 0x12,
	0x28, 0x0a, 0x0f, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x64, 0x79, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x09, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x08, 0x2e,
	0x42, 0x6f, 0x64, 0x79, 0x50, 0x6f, 0x73, 0x22, 0x00, 0x12, 0x2f, 0x0a, 0x14, 0x53, 0x6f, 0x6c,
	0x61, 0x72, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x09, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x41,
	0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x19, 0x4d, 0x61,
	0x6b, 0x65, 0x53, 0x6f, 0x6c, 0x61, 0x72, 0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x50, 0x72, 0x65,
	0x64, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x09, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x4e, 0x61,
	0x6d, 0x65, 0x1a, 0x0a, 0x2e, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x64, 0x69, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x39, 0x0a, 0x17, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x6f, 0x6c, 0x61, 0x72,
	0x53, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x12, 0x09, 0x2e, 0x42, 0x6f,
	0x64, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x11, 0x2e, 0x53, 0x6f, 0x6c, 0x61, 0x72, 0x53, 0x79,
	0x73, 0x74, 0x65, 0x6d, 0x53, 0x74, 0x61, 0x74, 0x73, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x2e,
	0x3b, 0x75, 0x6e, 0x69, 0x76, 0x65, 0x72, 0x73, 0x65, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_universe_rpc_proto_rawDescOnce sync.Once
	file_universe_rpc_proto_rawDescData = file_universe_rpc_proto_rawDesc
)

func file_universe_rpc_proto_rawDescGZIP() []byte {
	file_universe_rpc_proto_rawDescOnce.Do(func() {
		file_universe_rpc_proto_rawDescData = protoimpl.X.CompressGZIP(file_universe_rpc_proto_rawDescData)
	})
	return file_universe_rpc_proto_rawDescData
}

var file_universe_rpc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_universe_rpc_proto_goTypes = []interface{}{
	(*SolarSystemStats)(nil), // 0: SolarSystemStats
	(*BodyName)(nil),         // 1: BodyName
	(*BodyPos)(nil),          // 2: BodyPos
	(*AllBodies)(nil),        // 3: AllBodies
	(*NoInput)(nil),          // 4: NoInput
	nil,                      // 5: AllBodies.BodiesEntry
}
var file_universe_rpc_proto_depIdxs = []int32{
	5, // 0: AllBodies.Bodies:type_name -> AllBodies.BodiesEntry
	2, // 1: AllBodies.BodiesEntry.value:type_name -> BodyPos
	1, // 2: Greeter.GetBodyPosition:input_type -> BodyName
	1, // 3: Greeter.SolarSystemPositions:input_type -> BodyName
	1, // 4: Greeter.MakeSolarSystemPrediction:input_type -> BodyName
	1, // 5: Greeter.RequestSolarSystemStats:input_type -> BodyName
	2, // 6: Greeter.GetBodyPosition:output_type -> BodyPos
	3, // 7: Greeter.SolarSystemPositions:output_type -> AllBodies
	3, // 8: Greeter.MakeSolarSystemPrediction:output_type -> AllBodies
	0, // 9: Greeter.RequestSolarSystemStats:output_type -> SolarSystemStats
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_universe_rpc_proto_init() }
func file_universe_rpc_proto_init() {
	if File_universe_rpc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_universe_rpc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SolarSystemStats); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universe_rpc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyName); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universe_rpc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodyPos); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universe_rpc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AllBodies); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_universe_rpc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NoInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_universe_rpc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_universe_rpc_proto_goTypes,
		DependencyIndexes: file_universe_rpc_proto_depIdxs,
		MessageInfos:      file_universe_rpc_proto_msgTypes,
	}.Build()
	File_universe_rpc_proto = out.File
	file_universe_rpc_proto_rawDesc = nil
	file_universe_rpc_proto_goTypes = nil
	file_universe_rpc_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	//rpc SayHello (HelloRequest) returns (HelloReply) {}
	// Sends another greeting
	GetBodyPosition(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*BodyPos, error)
	SolarSystemPositions(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*AllBodies, error)
	MakeSolarSystemPrediction(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*AllBodies, error)
	RequestSolarSystemStats(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*SolarSystemStats, error)
}

type greeterClient struct {
	cc grpc.ClientConnInterface
}

func NewGreeterClient(cc grpc.ClientConnInterface) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) GetBodyPosition(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*BodyPos, error) {
	out := new(BodyPos)
	err := c.cc.Invoke(ctx, "/Greeter/GetBodyPosition", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) SolarSystemPositions(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*AllBodies, error) {
	out := new(AllBodies)
	err := c.cc.Invoke(ctx, "/Greeter/SolarSystemPositions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) MakeSolarSystemPrediction(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*AllBodies, error) {
	out := new(AllBodies)
	err := c.cc.Invoke(ctx, "/Greeter/MakeSolarSystemPrediction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) RequestSolarSystemStats(ctx context.Context, in *BodyName, opts ...grpc.CallOption) (*SolarSystemStats, error) {
	out := new(SolarSystemStats)
	err := c.cc.Invoke(ctx, "/Greeter/RequestSolarSystemStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	//rpc SayHello (HelloRequest) returns (HelloReply) {}
	// Sends another greeting
	GetBodyPosition(context.Context, *BodyName) (*BodyPos, error)
	SolarSystemPositions(context.Context, *BodyName) (*AllBodies, error)
	MakeSolarSystemPrediction(context.Context, *BodyName) (*AllBodies, error)
	RequestSolarSystemStats(context.Context, *BodyName) (*SolarSystemStats, error)
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) GetBodyPosition(context.Context, *BodyName) (*BodyPos, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBodyPosition not implemented")
}
func (*UnimplementedGreeterServer) SolarSystemPositions(context.Context, *BodyName) (*AllBodies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SolarSystemPositions not implemented")
}
func (*UnimplementedGreeterServer) MakeSolarSystemPrediction(context.Context, *BodyName) (*AllBodies, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MakeSolarSystemPrediction not implemented")
}
func (*UnimplementedGreeterServer) RequestSolarSystemStats(context.Context, *BodyName) (*SolarSystemStats, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestSolarSystemStats not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_GetBodyPosition_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BodyName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).GetBodyPosition(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/GetBodyPosition",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).GetBodyPosition(ctx, req.(*BodyName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_SolarSystemPositions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BodyName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SolarSystemPositions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/SolarSystemPositions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SolarSystemPositions(ctx, req.(*BodyName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_MakeSolarSystemPrediction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BodyName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).MakeSolarSystemPrediction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/MakeSolarSystemPrediction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).MakeSolarSystemPrediction(ctx, req.(*BodyName))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_RequestSolarSystemStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BodyName)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).RequestSolarSystemStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Greeter/RequestSolarSystemStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).RequestSolarSystemStats(ctx, req.(*BodyName))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBodyPosition",
			Handler:    _Greeter_GetBodyPosition_Handler,
		},
		{
			MethodName: "SolarSystemPositions",
			Handler:    _Greeter_SolarSystemPositions_Handler,
		},
		{
			MethodName: "MakeSolarSystemPrediction",
			Handler:    _Greeter_MakeSolarSystemPrediction_Handler,
		},
		{
			MethodName: "RequestSolarSystemStats",
			Handler:    _Greeter_RequestSolarSystemStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "universe_rpc.proto",
}
